# start with `docker compose up`
services:
  free-games-claimer:
    container_name: fgc # is printed in front of every output line
    image: ghcr.io/vogler/free-games-claimer # otherwise image name will be free-games-claimer-free-games-claimer
    build: .
    healthcheck: # not that useful, but linter complained, see Dockerfile
      test: "pgrep node"
      interval: 10s
      timeout: 5s
    ports:
      # - "5900:5900" # VNC server
      - "6080:6080" # noVNC (browser-based VNC client)
    volumes:
      - fgc:/fgc/data
    # command: bash -c "node epic-games; node gog"
    environment:
      # - EMAIL=foo@bar.org
      # - NOTIFY='tgram://...'
